Change daemon name and default values in OCF Script
Changed the daemon name from booth to boothd.
Default value for daemon was not set is now
"boothd" if OCF_RESKEY_daemon is empty.
Default value for type was always set to "site" even
when OCF_RESKEY_type was set to something other.
This now will be checkt and set correctly.
Removed overwriting of OCF_RESOURCE_INSTANCE_gloablly_unique with
false. Because this is already captured in booth_validate function.
If its overwritten no error message will be displayed.

Fixes issues like this:
OCF_ROOT=/usr/lib/ocf OCF_RESKEY_daemon=booth \
/usr/lib/ocf/resource.d/pacemaker/booth-site validate-all
ERROR: Setup problem: couldn't find command:

Signed-off-by: Joerg Frede <frede@b1-systems.de>