Fix compiler warning/-Werror.
http://gcc.gnu.org/bugzilla/show_bug.cgi?id=40635 applies, though.
Even if "rv" in main is renamed:
  main.c:1232:18: error: ‘rv’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
    return (rv >= 0 && rv < 0x70) ? rv : 1;